<?php

class APlayerHero {

    public function getAll() {
        $idPlayer = validateID($_GET["idPlayer"]);
        return '[
        {
            "id_hero": 8740,
            "name": "اغسطس",
            "lvl": 218,
            "ord": 1,
            "ultra_p": 8,
            "exp": 15321276,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 16,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 23,
            "p_b_b": 22,
            "p_b_c": 8,
            "points": 840,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 49500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 8740,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 0,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 8740,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 67854,
                "f_2_num": 71959,
                "f_3_num": 62294,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": {
                    "id_equip": 1412,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "boot",
                    "type": "bright",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-02-10 02:47:29"
                },
                "armor": {
                    "id_equip": 538,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "armor",
                    "type": "mili",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-09 00:51:26"
                },
                "shield": {
                    "id_equip": 1372,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "shield",
                    "type": "bright",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-02-07 23:43:35"
                },
                "helmet": {
                    "id_equip": 919,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "helmet",
                    "type": "bright",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-30 02:39:49"
                },
                "sword": {
                    "id_equip": 1371,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "sword",
                    "type": "bright",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-02-07 23:43:19"
                },
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 7583,
            "name": "اليس",
            "lvl": 217,
            "ord": 2,
            "ultra_p": 8,
            "exp": 10694954,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 10,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 17,
            "p_b_b": 20,
            "p_b_c": 20,
            "points": 819,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 57000,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 7583,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 0,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 7583,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 73016,
                "f_2_num": 67236,
                "f_3_num": 71882,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": {
                    "id_equip": 1451,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "boot",
                    "type": "bright",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-02-13 00:18:54"
                },
                "armor": {
                    "id_equip": 979,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "armor",
                    "type": "mili",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-02-01 01:53:37"
                },
                "shield": {
                    "id_equip": 901,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "shield",
                    "type": "bright",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-29 00:21:42"
                },
                "helmet": {
                    "id_equip": 1204,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "helmet",
                    "type": "bright",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-02-03 02:37:10"
                },
                "sword": {
                    "id_equip": 1503,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "sword",
                    "type": "bright",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-02-15 22:24:24"
                },
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 10206,
            "name": "سيورس",
            "lvl": 205,
            "ord": 3,
            "ultra_p": 8,
            "exp": 12445716,
            "loyal": 70,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 10,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 10,
            "p_b_b": 14,
            "p_b_c": 35,
            "points": 765,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 67500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 10206,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 0,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 10206,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 69434,
                "f_2_num": 87089,
                "f_3_num": 58161,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": {
                    "id_equip": 833,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "boot",
                    "type": "bright",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-25 14:50:22"
                },
                "armor": {
                    "id_equip": 1117,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "armor",
                    "type": "mili",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-02-01 22:59:57"
                },
                "shield": {
                    "id_equip": 849,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "shield",
                    "type": "fearless",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-26 02:32:51"
                },
                "helmet": {
                    "id_equip": 834,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "helmet",
                    "type": "bright",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-25 14:50:29"
                },
                "sword": {
                    "id_equip": 748,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "sword",
                    "type": "bright",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-20 00:55:26"
                },
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 11538,
            "name": "هكس",
            "lvl": 200,
            "ord": 4,
            "ultra_p": 8,
            "exp": 16373817,
            "loyal": 70,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 18,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 8,
            "p_b_b": 21,
            "p_b_c": 27,
            "points": 780,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 41500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 11538,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 0,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 11538,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 65328,
                "f_2_num": 71305,
                "f_3_num": 73132,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": {
                    "id_equip": 846,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "boot",
                    "type": "fearless",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-26 02:31:03"
                },
                "armor": {
                    "id_equip": 246,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "armor",
                    "type": "fearless",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2019-12-19 01:00:36"
                },
                "shield": {
                    "id_equip": 814,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "shield",
                    "type": "fearless",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-24 00:23:11"
                },
                "helmet": {
                    "id_equip": 785,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "helmet",
                    "type": "bright",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-21 23:16:53"
                },
                "sword": {
                    "id_equip": 848,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "sword",
                    "type": "fearless",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-26 02:31:50"
                },
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 3579,
            "name": "بطليموس",
            "lvl": 210,
            "ord": 10,
            "ultra_p": 8,
            "exp": 34656765,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 2,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 22,
            "p_b_b": 17,
            "p_b_c": 16,
            "points": 755,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 50000,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 3579,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 0,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 3579,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 250000,
                "f_2_num": 1,
                "f_3_num": 1,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": {
                    "id_equip": 1373,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "boot",
                    "type": "fearless",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-02-07 23:48:45"
                },
                "armor": {
                    "id_equip": 1411,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "armor",
                    "type": "mili",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-02-10 01:02:07"
                },
                "shield": {
                    "id_equip": 428,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "shield",
                    "type": "fearless",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-04 01:54:30"
                },
                "helmet": {
                    "id_equip": 910,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "helmet",
                    "type": "bright",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-29 22:16:39"
                },
                "sword": {
                    "id_equip": 904,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "sword",
                    "type": "fearless",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-29 00:58:00"
                },
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 2418,
            "name": "هكس",
            "lvl": 218,
            "ord": 14,
            "ultra_p": 8,
            "exp": 42034522,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 12,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 18,
            "p_b_b": 23,
            "p_b_c": 18,
            "points": 808,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 47500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 2418,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 0,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 2418,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 250000,
                "f_2_num": 1,
                "f_3_num": 1,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": {
                    "id_equip": 115,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "boot",
                    "type": "lion",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2019-11-29 01:20:34"
                },
                "armor": {
                    "id_equip": 847,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "armor",
                    "type": "lion",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-26 02:31:24"
                },
                "shield": {
                    "id_equip": 1491,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "shield",
                    "type": "fearless",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-02-15 03:04:04"
                },
                "helmet": {
                    "id_equip": 360,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "helmet",
                    "type": "mili",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-01 22:35:43"
                },
                "sword": {
                    "id_equip": 1492,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "sword",
                    "type": "fearless",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-02-15 03:04:18"
                },
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 7452,
            "name": "القاهر",
            "lvl": 235,
            "ord": 16,
            "ultra_p": 8,
            "exp": 44772920,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 10,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 16,
            "p_b_b": 10,
            "p_b_c": 32,
            "points": 849,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 65500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 7452,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 0,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 7452,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 250000,
                "f_2_num": 1,
                "f_3_num": 1,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": {
                    "id_equip": 338,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "boot",
                    "type": "lion",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2019-12-28 01:20:46"
                },
                "armor": {
                    "id_equip": 143,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "armor",
                    "type": "lion",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2019-11-29 01:20:34"
                },
                "shield": {
                    "id_equip": 1375,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "shield",
                    "type": "lion",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-02-08 00:18:07"
                },
                "helmet": {
                    "id_equip": 102,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "helmet",
                    "type": "fearless",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2019-11-24 22:52:44"
                },
                "sword": {
                    "id_equip": 493,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "sword",
                    "type": "mili",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-06 02:02:51"
                },
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 1992,
            "name": "القاهر",
            "lvl": 249,
            "ord": 18,
            "ultra_p": 8,
            "exp": 37960821,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 9,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 23,
            "p_b_b": 21,
            "p_b_c": 14,
            "points": 935,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 47500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 1992,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 0,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 1992,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 66893,
                "f_2_num": 66631,
                "f_3_num": 96172,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": {
                    "id_equip": 815,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "boot",
                    "type": "lion",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2020-01-24 00:23:15"
                },
                "armor": {
                    "id_equip": 177,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "armor",
                    "type": "lion",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2019-11-29 01:52:29"
                },
                "shield": {
                    "id_equip": 170,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "shield",
                    "type": "lion",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2019-11-29 01:52:29"
                },
                "helmet": {
                    "id_equip": 129,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "helmet",
                    "type": "lion",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2019-11-29 01:20:34"
                },
                "sword": {
                    "id_equip": 156,
                    "id_player": 499,
                    "sp_attr": 0,
                    "part": "sword",
                    "type": "lion",
                    "on_hero": 1,
                    "cat": "main",
                    "lvl": 1,
                    "time_stamp": "2019-11-29 01:52:29"
                },
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 7307,
            "name": "اليكس",
            "lvl": 255,
            "ord": 21,
            "ultra_p": 8,
            "exp": 12657735,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 2,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 23,
            "p_b_b": 15,
            "p_b_c": 19,
            "points": 953,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 65500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 7307,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 0,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 7307,
                "id_player": 499,
                "f_1_type": 0,
                "f_2_type": 0,
                "f_3_type": 0,
                "f_1_num": 0,
                "f_2_num": 0,
                "f_3_num": 0,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": null,
                "armor": null,
                "shield": null,
                "helmet": null,
                "sword": null,
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 6977,
            "name": "مصطفى",
            "lvl": 255,
            "ord": 22,
            "ultra_p": 8,
            "exp": 6806696,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 1,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 16,
            "p_b_b": 18,
            "p_b_c": 23,
            "points": 959,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 64500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 6977,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 0,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 6977,
                "id_player": 499,
                "f_1_type": 0,
                "f_2_type": 0,
                "f_3_type": 0,
                "f_1_num": 0,
                "f_2_num": 0,
                "f_3_num": 0,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": null,
                "armor": null,
                "shield": null,
                "helmet": null,
                "sword": null,
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 8166,
            "name": "الاسد",
            "lvl": 255,
            "ord": 24,
            "ultra_p": 8,
            "exp": 2428473,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 4,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 21,
            "p_b_b": 18,
            "p_b_c": 17,
            "points": 946,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 66500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 8166,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 1579991750,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 8166,
                "id_player": 499,
                "f_1_type": 0,
                "f_2_type": 0,
                "f_3_type": 0,
                "f_1_num": 0,
                "f_2_num": 0,
                "f_3_num": 0,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": null,
                "armor": null,
                "shield": null,
                "helmet": null,
                "sword": null,
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 5555,
            "name": "ماجد",
            "lvl": 255,
            "ord": 25,
            "ultra_p": 8,
            "exp": 3697324,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 11,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 25,
            "p_b_b": 14,
            "p_b_c": 13,
            "points": 975,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 54000,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 5555,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 1579819782,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 5555,
                "id_player": 499,
                "f_1_type": 0,
                "f_2_type": 0,
                "f_3_type": 0,
                "f_1_num": 0,
                "f_2_num": 0,
                "f_3_num": 0,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": null,
                "armor": null,
                "shield": null,
                "helmet": null,
                "sword": null,
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 5858,
            "name": "القاهر",
            "lvl": 255,
            "ord": 26,
            "ultra_p": 8,
            "exp": 7213457,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 0,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 10,
            "p_b_b": 23,
            "p_b_c": 19,
            "points": 951,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 62500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 5858,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 1579650778,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 5858,
                "id_player": 499,
                "f_1_type": 0,
                "f_2_type": 0,
                "f_3_type": 0,
                "f_1_num": 0,
                "f_2_num": 0,
                "f_3_num": 0,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": null,
                "armor": null,
                "shield": null,
                "helmet": null,
                "sword": null,
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 4645,
            "name": "زين",
            "lvl": 255,
            "ord": 27,
            "ultra_p": 8,
            "exp": 7069890,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 19,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 13,
            "p_b_b": 19,
            "p_b_c": 26,
            "points": 986,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 42000,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 4645,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 1579034574,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 4645,
                "id_player": 499,
                "f_1_type": 0,
                "f_2_type": 0,
                "f_3_type": 0,
                "f_1_num": 0,
                "f_2_num": 0,
                "f_3_num": 0,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": null,
                "armor": null,
                "shield": null,
                "helmet": null,
                "sword": null,
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 4557,
            "name": "اليس",
            "lvl": 255,
            "ord": 32,
            "ultra_p": 8,
            "exp": 24555483,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 18,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 18,
            "p_b_b": 16,
            "p_b_c": 25,
            "points": 989,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 42500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 4557,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 1579034580,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 4557,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 77835,
                "f_2_num": 87750,
                "f_3_num": 75954,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": null,
                "armor": null,
                "shield": null,
                "helmet": null,
                "sword": null,
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 6467,
            "name": "كليوباترا",
            "lvl": 255,
            "ord": 33,
            "ultra_p": 8,
            "exp": 9750082,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 7,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 16,
            "p_b_b": 20,
            "p_b_c": 14,
            "points": 986,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 43500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 6467,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 1578857133,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 6467,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 77827,
                "f_2_num": 92361,
                "f_3_num": 78692,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": null,
                "armor": null,
                "shield": null,
                "helmet": null,
                "sword": null,
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 3268,
            "name": "مارس",
            "lvl": 255,
            "ord": 35,
            "ultra_p": 8,
            "exp": 22501800,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 6,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 19,
            "p_b_b": 18,
            "p_b_c": 21,
            "points": 993,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 40500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 3268,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 1578857587,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 3268,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 60584,
                "f_2_num": 86923,
                "f_3_num": 60561,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": null,
                "armor": null,
                "shield": null,
                "helmet": null,
                "sword": null,
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 4646,
            "name": "مارس",
            "lvl": 255,
            "ord": 37,
            "ultra_p": 8,
            "exp": 16584227,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 15,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 14,
            "p_b_b": 10,
            "p_b_c": 35,
            "points": 980,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 49500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 4646,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 1579560078,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 4646,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 56263,
                "f_2_num": 69304,
                "f_3_num": 57482,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": null,
                "armor": null,
                "shield": null,
                "helmet": null,
                "sword": null,
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 5718,
            "name": "يويليوس",
            "lvl": 255,
            "ord": 38,
            "ultra_p": 8,
            "exp": 6421376,
            "loyal": 100,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 18,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 10,
            "p_b_b": 17,
            "p_b_c": 23,
            "points": 994,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 41500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 5718,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 1579559448,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 5718,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 61565,
                "f_2_num": 112827,
                "f_3_num": 67725,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": null,
                "armor": null,
                "shield": null,
                "helmet": null,
                "sword": null,
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 11537,
            "name": "اليس",
            "lvl": 101,
            "ord": 38,
            "ultra_p": 8,
            "exp": 230106,
            "loyal": 70,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 16,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 21,
            "p_b_b": 15,
            "p_b_c": 22,
            "points": 413,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 40500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 11537,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 0,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 11537,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 12502,
                "f_2_num": 11272,
                "f_3_num": 12503,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": null,
                "armor": null,
                "shield": null,
                "helmet": null,
                "sword": null,
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 13208,
            "name": "بطليموس",
            "lvl": 105,
            "ord": 39,
            "ultra_p": 8,
            "exp": 709258,
            "loyal": 70,
            "power": 150,
            "id_city": 326,
            "id_player": 499,
            "avatar": 5,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 9,
            "p_b_b": 16,
            "p_b_c": 32,
            "points": 395,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 40500,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 13208,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 0,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 13208,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 57529,
                "f_2_num": 59892,
                "f_3_num": 49974,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": null,
                "armor": null,
                "shield": null,
                "helmet": null,
                "sword": null,
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 10927,
            "name": "يورك",
            "lvl": 86,
            "ord": 40,
            "ultra_p": 8,
            "exp": 319725,
            "loyal": 70,
            "power": 136,
            "id_city": 326,
            "id_player": 499,
            "avatar": 7,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 12,
            "p_b_b": 10,
            "p_b_c": 33,
            "points": 344,
            "point_a": 10,
            "point_b": 10,
            "point_c": 10,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 42000,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 10927,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 0,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 10927,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 57529,
                "f_2_num": 59999,
                "f_3_num": 55000,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": null,
                "armor": null,
                "shield": null,
                "helmet": null,
                "sword": null,
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        },
        {
            "id_hero": 2712,
            "name": "الملك",
            "lvl": 4,
            "ord": 41,
            "ultra_p": 0,
            "exp": 506622,
            "loyal": 70,
            "power": 54,
            "id_city": 326,
            "id_player": 499,
            "avatar": 14,
            "in_city": 1,
            "b_lvl": 1,
            "p_b_a": 21,
            "p_b_b": 11,
            "p_b_c": 21,
            "points": 12,
            "point_a": 15,
            "point_b": 20,
            "point_c": 15,
            "point_a_plus": 3,
            "point_b_plus": 0,
            "point_c_plus": 0,
            "console": 0,
            "cap": 42000,
            "power_ls": 1585244986,
            "medal": {
                "id_hero": 2712,
                "medal_ceasro": 0,
                "medal_den": 0,
                "medal_leo": 0,
                "ceaser_eagle": 0
            },
            "army": {
                "id_hero": 2712,
                "id_player": 499,
                "f_1_type": 1,
                "f_2_type": 1,
                "f_3_type": 1,
                "f_1_num": 987,
                "f_2_num": 990,
                "f_3_num": 994,
                "b_1_type": 0,
                "b_2_type": 0,
                "b_3_type": 0,
                "b_1_num": 0,
                "b_2_num": 0,
                "b_3_num": 0
            },
            "equip": {
                "boot": null,
                "armor": null,
                "shield": null,
                "helmet": null,
                "sword": null,
                "belt": null,
                "necklace": null,
                "pendant": null,
                "ring": null,
                "steed": null
            }
        }]';
    }

}
